In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/car_data.csv')

In [3]:
df.head()

name  year  selling_price  km_driven    fuel  \
0             Maruti 800 AC  2007          60000      70000  Petrol   
1  Maruti Wagon R LXI Minor  2007         135000      50000  Petrol   
2      Hyundai Verna 1.6 SX  2012         600000     100000  Diesel   
3    Datsun RediGO T Option  2017         250000      46000  Petrol   
4     Honda Amaze VX i-DTEC  2014         450000     141000  Diesel   

  seller_type transmission         owner  
0  Individual       Manual   First Owner  
1  Individual       Manual   First Owner  
2  Individual       Manual   First Owner  
3  Individual       Manual   First Owner  
4  Individual       Manual  Second Owner

In [4]:
df.isnull().sum()

name             0
year             0
selling_price    0
km_driven        0
fuel             0
seller_type      0
transmission     0
owner            0
dtype: int64

In [5]:
df['owner'].value_counts()

owner
First Owner             2832
Second Owner            1106
Third Owner              304
Fourth & Above Owner      81
Test Drive Car            17
Name: count, dtype: int64

In [6]:
df['seller_type'].value_counts()

seller_type
Individual          3244
Dealer               994
Trustmark Dealer     102
Name: count, dtype: int64

Encoding the data

In [7]:
x = df.iloc[:, [1,3,4,6]].values
y = df.iloc[:, 2].values

In [10]:
x

array([[2007, 70000, 'Petrol', 'Manual'],
       [2007, 50000, 'Petrol', 'Manual'],
       [2012, 100000, 'Diesel', 'Manual'],
       ...,
       [2009, 83000, 'Petrol', 'Manual'],
       [2016, 90000, 'Diesel', 'Manual'],
       [2016, 40000, 'Petrol', 'Manual']], dtype=object)

In [11]:
x[:,2]

array(['Petrol', 'Petrol', 'Diesel', ..., 'Petrol', 'Diesel', 'Petrol'],
      dtype=object)

In [13]:
from sklearn.preprocessing import LabelEncoder
lb = LabelEncoder()
x[:, 2] = lb.fit_transform(x[:, 2])
lb1 = LabelEncoder()
x[:, 3] = lb1.fit_transform(x[:, 3])

In [14]:
x[:, 2]

array([4, 4, 1, ..., 4, 1, 4], dtype=object)

SPLITTING THE DATA INTO TRAINING AND TEST SET

In [19]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.05, random_state=0)

print(x_train)

[[2016 36000 1 1]
 [2014 70000 4 1]
 [2016 23000 4 1]
 ...
 [2016 22000 4 1]
 [2015 70000 1 1]
 [2013 62000 4 1]]


TRAINING THE MODEL

In [20]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators=300, random_state=0)
regressor.fit(x_train, y_train)

RandomForestRegressor(n_estimators=300, random_state=0)

In [21]:
accuracy = regressor.score(x_test, y_test)
print(accuracy*100, '%')

85.74236935963135 %


Performing a Test on given input

In [22]:
new_data = [ 2017, 70000, 'Petrol', 'Manual']
new_data[2] = lb.transform([new_data[2]])[0]
new_data[3] = lb1.transform([new_data[3]])[0]

In [23]:
print(new_data)
regressor.predict([new_data])

[2017, 70000, np.int64(4), np.int64(1)]


array([415541.61767196])

Saving the model and encoder using Pickle

In [24]:
import pickle
pickle.dump(regressor, open('car_price_regressor.pkl', 'wb'))
pickle.dump(lb, open('lb.pkl', 'wb'))
pickle.dump(lb1, open('lb1.pkl', 'wb'))